export interface Newstudent {
 highSchoolPercentage: number
 isOutsideSchool: boolean
 highSchoolId: number
 highSchoolName: string
 firstName: string
 secondName: string
 thirdName: string
 fourthName: string
 nationalId: string
 phone: string
 birthDate: string
 gender: number
 religion: number
 hasSpecialNeeds: boolean
 academicStudentCode: string
 academicYear: string
 email: string
 isMarried: boolean
 currentScore: number
 qrImagePath: string
 guardianId: number
 guardianFullName: string
 guardianPhone: string
}
export interface OldStudent {
 oldStudentId: number
 previousYearGrade: number
 gradePercentage: number
 previousYearHosting: boolean
 firstName: string
 secondName: string
 thirdName: string
 fourthName: string
 nationalId: string
 phone: string
 birthDate: string
 gender: number
 religion: number
 hasSpecialNeeds: boolean
 academicStudentCode: string
 academicYear: string
 email: string
 isMarried: boolean
 currentScore: number
 qrImagePath: string
 guardianId: number
 guardianFullName: string
 guardianPhone: string
}