name: Angular CI/CD

permissions:
  contents: write # Allows GitHub Actions to push changes to the repository

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm" # Cache npm dependencies for faster builds

      - name: Install dependencies
        run: npm ci # Faster and more reliable than `npm install`

      - name: Build project
        run: |
          set -e # Stop execution on error
          npm run build -- --configuration production

      - name: Identify build directory
        run: echo "DIST_DIR=$(ls -d ./dist/*/browser)" >> $GITHUB_ENV

      - name: Ensure docs/browser folder exists
        run: mkdir -p docs/browser

      - name: Move build files to docs/browser
        run: mv $DIST_DIR/* docs/browser/ || echo "No files to move"

      - name: Disable Jekyll (Fix GitHub Pages Error)
        run: touch docs/browser/.nojekyll

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/browser
